### PR TITLE
Remove contribution model

### PR DESCRIPTION
**Pull request by ChrisSfanos**

### CODE REVIEW

**Comment by oskardudycz** [comment]
@ChrisSfanos what does this removal mean for the current projects using the contribution model (like Marten)?

**Comment by ChrisSfanos** [comment]
There are no plans (that I'm aware of) to change how any existing projects are handled.  This is intended for new projects only

**Comment by oskardudycz** [comment]
@ChrisSfanos thank you for the answer, glad to read that it won't change our current status. 

What's the motivation for removing the contribution model? Is there available discussion that could be seen publicly (or internally for Foundation members)? This seems to be a significant change for the new projects.

**Comment by ChrisSfanos** [comment]
That I don't have too much detailed insight that I can share - following up with @clairernovotny  is probably the best path

**Comment by oskardudycz** [comment]
@clairernovotny could you elaborate on that change?

**Comment by peteraritchie** [comment]
This seems like something @johnvpetersen would be interested in

**Pull request merged**
