### PR TITLE
Convert membership application template from Markdown to YAML Form.

### PR DESCRIPTION
**Pull request by jmelosegui**
This pull request proposes converting the existing Markdown Issue Template to a [YAML Issue Form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) in GitHub. 
By transitioning to the YAML format, we can have the following benefits:

1. Eliminate Empty Submissions: YAML supports built-in validation, allowing us to ensure all required fields are filled correctly before submitting the form.

2. Improved Clarity: Issue Forms provide a structured and organized format, making it easier for contributors to understand and complete the issue form accurately.

_Note: Github Issue forms are currently in beta._

### CODE REVIEW

**Comment by jmelosegui** [comment]
@dotnet-policy-service agree

**Comment by jmelosegui** [comment]
@sbwalker @ChrisSfanos [This](https://github.com/jmelosegui/TestGithubForms/issues/new?assignees=sbwalker%2CChrisSfanos&labels=project+application%2Cproject+support&projects=&template=MembershipApplication.yml&title=Issue%3A+New+.NET+Foundation+Project+Application) is a working example of the proposed form.

**Comment by sbwalker** [comment]
@ChrisSfanos I think this is a good idea as it is an improvement over the current form. I approve the change as I believe it will be helpful for the community. If you agree, please merge the PR.

**Comment by ChrisSfanos** [comment]
Sounds good - this is merged

**Pull request merged**
