### PR TITLE
WIP: Alternative proposal for considering health and maturity of a project

### PR DESCRIPTION
**Pull request by SeanKilleen**
_[NOTE: This is a draft PR. I am thinking out loud as I form my thoughts in-between baby duties 😄. Feel free to follow along but it's not a real proposal until I convert this from a draft.]_ 

This is a thought exercise to build upon the existing project team structure and think about it more in terms of the outcomes and capabilities that we want to foster in projects.

## First up -- I really like what you all are doing.

The Foundation, its committee members, and its Board do not have an easy job and I appreciate everyone stepping up. Putting things like this in public places where they can be discussed and proposals can be made is a very good thing IMO. 👍 Thanks for that.

## Concerns with the idea of "Health" and "Maturity"

Terms like `Health` and `Maturity`, by their nature, are somewhat prescriptive, because they imply that the view of the authors on these matters is objective. But of course, the authors could not possibly know what universally makes a project healthy and mature in terms of practices, especially given the breadth of projects the Foundation is (and will be) involved with.

As a result, it is tempting to rely on proxy metrics -- such as stars or forks -- to think about health, and to rely on practices that may not be universally applicable to attempt to fit things neatly into a path of maturity.

This also overlooks an opportunity for the foundation to play a key role in supporting -- or fostering support for -- project outcomes and capabilities, rather than as an arbiter of maturity.

## Alternatives to Health and Maturity: Capabilities and Confidence

Rather than the Health and Maturity of a project, I think it might be helpful to think in terms of capabilities and confidence.

* What aspects of a project does the .NET Foundation want to be confident about or have the maintainers be confident about?
* What capabilities should a project strive for? 

## Why use these instead?

If the desire is to ensure a project's overall performance and ability to deliver, the book _Accelerate_ provides some great examples of capabilities that are statistically correlated with high performing teams and products. I'd suggest adopting this list wholesale as it's a recognized reference point and a lot of research went into it.

Outlining points of confidence allows for a few things:

* It applies a spectrum that isn't linked to positive or negative.
* It allows for non-prescriptive suggestions -- there are multiple ways for projects to state why they are confident in a certain outcome. 
* It enables the Foundation or others to suggest steps that might increase confidence
* It makes the Foundation's goals and aims explicit and transparent because a measure of confidence implies confidence in an outcome.
* It allows for a discussion around what could help the foundation or maintainers feel more confident without constraining the conversation to ideas of objective maturity, which maintainers and the foundation might quite reasonably disagree on.

## Examples

The below is only a small example of how these techniques could be applied. I'll attempt to convert the current approach to these approaches in my PR.

### Capabilities

Say we want to ensure that a project is able to continuously deliver -- something linked with high-performance outcomes in Accelerate. We might ask questions on a 7-point Likert scale (1 = strongly disagree, 7 = strongly agree), such as:

* My project uses version control for all production artifacts
* My project's deployment process is automated
* My project utilizes continuous integration
* My project utilizes trunk-based development methods
* My project uses test automation
* My project is continuously delivered.

These are on a scale, because a project does not necessarily need to be at a 7 to succeed, and it forms the basis for a reliable conversation.

### Confidence Meters

These must ultimately be defined by the Foundation, but I'll attempt to intuit some and suggest my own. 

One example is that the .NET Foundation wants to ensure that projects are actively maintained and that they don't stagnate (a great goal IMO.) Again, some Likert-scale questions could be used here (1 - Very Low Confidence, 7 - Very High Confidence). Imagine questions such as the below, with a box that allows for a "why?" answer alongside each.

* A pull request submitted to this repository will be accepted
* Suggestions for the project are considered in a timely manner
* Should a core team member stop contributing, this project will remain actively mantained.

High confidence and explanations in these questions may yield great reference material for other projects. Low confidence and explanations in these questions could help underscore concrete actions that the .NET Foundation can take to support projects on this journey.

----

That's enough of a long-winded explanation for this PR. I'll attempt to show what I mean in the changes to the current text.

### CODE REVIEW

**Comment by glennawatson** [comment]
Hey @SeanKilleen did you want to take this one further?

**Comment by SeanKilleen** [comment]
It did not seem to gain much traction so we can close it out. If I want to get a draft of it in place I'll try to do it outside of the foundation and then re-propose it.

**Comment by sbwalker** [comment]
The current Project Charter has provided a good framework for the Foundation for the past 3 years... but it always open to suggestions and improvements. 

For example the Project Committee recently made a proposal to the BOD in regards to clarifying the criteria related to the "retirement of projects". The BOD voted to approve the proposal last month and it will be added to the Charter once the communication plans are finalized.

**Comment by SeanKilleen** [comment]
Yep @sbwalker, this is something from 3 years ago so is not something I feel the need to continue, and would need to start from scratch to propose changes anyway. 👍

**Pull request closed without merging**
